# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['multiply', 'difference']

# Cell
def multiply(a, b):
    "Multiply a*b"
    return a*b

# Cell
def difference(a, b):
    "difference a+b"
    return a+b