# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'multiply', 'read_image']

# Cell
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# Cell
def multiply(a, b):
    "Multiplies a and b"
    return a*b

# Cell
def read_image(path):
    return Image.open(path)